### ISSUE TITLE
[Android] Cannot log screenshot because of Javax.imageio is not available for Android

### ISSUE THREAD

**Issue by neestell** [reportportal/android-kotlin-example#1]
A sample project for Kotlin does not work correctly on the last step. If you try log a screenshot test app throws an exception 
`.NoClassDefFoundError: Failed resolution of: Ljavax/imageio/ImageIO;` What should I do to resolve the issue?
Thank you

**Comment by HardNorth** [comment]
Please inspect your libraries, because the example works for me well without changing anything:
![Screenshot 2024-03-12 at 18 06 40](https://github.com/reportportal/android-kotlin-example/assets/4364466/fda70af1-7cfc-408e-84ca-899fedc03860)
