### ISSUE TITLE
Certificates Error

### ISSUE THREAD

**Issue by luvgeist** [reportportal/android-kotlin-example#2]
I've been trying to pass the **junit5:connectedAndroidTest** for a while and it gives me the following certificate error:

INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed collecting certificates for /data/app/vmdl434089841.tmp/base.apk: Failed to collect certificates from /data/app/vmdl434089841.tmp/base.apk: Attempt to get length of null array

I've also been looking for certificates in the repo but I couldn't fine none!

**Comment by HardNorth** [comment]
@luvdevs Yes, because since some version of Android SDK signing APKs is mandatory, even ones with tests. I believe this is a user area of responsibility. To avoid this you can use "junit5:connectedDebugAndroidTest" task, this one not requiring signed APK.
